//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type UserRole string

const (
	UserRole_Admin      UserRole = "admin"
	UserRole_Client     UserRole = "client"
	UserRole_Freelancer UserRole = "freelancer"
)

var UserRoleAllValues = []UserRole{
	UserRole_Admin,
	UserRole_Client,
	UserRole_Freelancer,
}

func (e *UserRole) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "admin":
		*e = UserRole_Admin
	case "client":
		*e = UserRole_Client
	case "freelancer":
		*e = UserRole_Freelancer
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for UserRole enum")
	}

	return nil
}

func (e UserRole) String() string {
	return string(e)
}
